//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAHN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Check_List()
        {
            this.Home_Needs = new HashSet<Home_Needs>();
        }
    
        public int Id { get; set; }
        public string Date { get; set; }
        public string Category { get; set; }
        public string ToDo { get; set; }
        public string Location { get; set; }
        public string Property1 { get; set; }
        public int StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Home_Needs> Home_Needs { get; set; }
        public virtual Status Status { get; set; }
    }
}
