//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAHN
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseTracker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpenseTracker()
        {
            this.ThisMonths = new HashSet<ThisMonth>();
            this.ExpenseTrackerAndHomeNeeds = new HashSet<ExpenseTrackerAndHomeNeeds>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PersonId { get; set; }
        public int Person_DetailsId { get; set; }
        public int ExpenseId { get; set; }
        public int Home_NeedsId { get; set; }
        public int Report_TotalId { get; set; }
        public int Report_By_PersonId { get; set; }
        public int Report_By_MonthId { get; set; }
        public int Report_By_DateId { get; set; }
        public int Report_By_Search_And_FilterId { get; set; }
        public int Family_MembersId { get; set; }
        public int PersonId1 { get; set; }
        public int Report_By_Search_And_FilterId1 { get; set; }
        public int Report_By_DateId1 { get; set; }
        public int Report_By_MonthId1 { get; set; }
    
        public virtual Person_Details Person_Details { get; set; }
        public virtual Expense Expense { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThisMonth> ThisMonths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseTrackerAndHomeNeeds> ExpenseTrackerAndHomeNeeds { get; set; }
        public virtual Report_Total Report_Total { get; set; }
        public virtual Report_By_Person Report_By_Person { get; set; }
        public virtual Person Person { get; set; }
        public virtual Report_By_Search_And_Filter Report_By_Search_And_Filter { get; set; }
        public virtual Report_By_Date Report_By_Date { get; set; }
        public virtual Report_By_Month Report_By_Month { get; set; }
    }
}
