//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAHN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExpenseTrackerContainer : DbContext
    {
        public ExpenseTrackerContainer()
            : base("name=ExpenseTrackerContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ExpenseTracker> ExpenseTrackers { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Person_Details> Person_Details { get; set; }
        public virtual DbSet<Person_Type> Person_Type { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<Expense_category> Expense_category { get; set; }
        public virtual DbSet<ThisMonth> ThisMonths { get; set; }
        public virtual DbSet<ExpenseTrackerAndHomeNeeds> ExpenseTrackerAndHomeNeeds { get; set; }
        public virtual DbSet<Report_Total> Report_Total { get; set; }
        public virtual DbSet<Report_By_Person> Report_By_Person { get; set; }
        public virtual DbSet<Report_By_Month> Report_By_Month { get; set; }
        public virtual DbSet<Report_By_Date> Report_By_Date { get; set; }
        public virtual DbSet<Report_By_Search_And_Filter> Report_By_Search_And_Filter { get; set; }
        public virtual DbSet<Home_Needs> Home_Needs { get; set; }
        public virtual DbSet<Monthly_Needs> Monthly_Needs { get; set; }
        public virtual DbSet<Loans> Loans { get; set; }
        public virtual DbSet<Check_List> Check_List { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Family_Members> Family_Members { get; set; }
        public virtual DbSet<LicencedFor> LicencedFors { get; set; }
        public virtual DbSet<Member_Type> Member_Type { get; set; }
        public virtual DbSet<Home_Ownership> Home_Ownership { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<OwnershipOf> OwnershipOfs { get; set; }
        public virtual DbSet<Having_Licence> Having_Licence { get; set; }
        public virtual DbSet<VehileKm_Tracker> VehileKm_Tracker { get; set; }
        public virtual DbSet<Trip_Check_List> Trip_Check_List { get; set; }
        public virtual DbSet<Trip_For> Trip_For { get; set; }
        public virtual DbSet<Taken> Takens { get; set; }
        public virtual DbSet<Need_Name> Need_Name { get; set; }
    }
}
