//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAHN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family_Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Family_Members()
        {
            this.Home_Needs = new HashSet<Home_Needs>();
            this.Home_Ownership = new HashSet<Home_Ownership>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email_id { get; set; }
        public long Adhar_Number { get; set; }
        public long PAN_CardNumber { get; set; }
        public long Election_CardNumber { get; set; }
        public long Licence_Number { get; set; }
        public string Bank_Account_detais { get; set; }
        public long Mobile_Number1 { get; set; }
        public long Mobile_Number2 { get; set; }
        public long Landline { get; set; }
        public string Occupation { get; set; }
        public string Occupation_Location { get; set; }
        public int Home_OwnershipId { get; set; }
        public int LicencedForId { get; set; }
        public int Member_TypeId { get; set; }
        public int Home_OwnershipId1 { get; set; }
        public int LicencedForId1 { get; set; }
    
        public virtual Member_Type Member_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Home_Needs> Home_Needs { get; set; }
        public virtual LicencedFor LicencedFor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Home_Ownership> Home_Ownership { get; set; }
    }
}
