//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAHN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home_Ownership
    {
        public int Id { get; set; }
        public string Rent { get; set; }
        public string Own { get; set; }
        public int Family_MembersId { get; set; }
    
        public virtual Family_Members Family_Members { get; set; }
    }
}
