//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAHN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home_Needs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Home_Needs()
        {
            this.ExpenseTrackerAndHomeNeeds = new HashSet<ExpenseTrackerAndHomeNeeds>();
        }
    
        public int Id { get; set; }
        public string Entity { get; set; }
        public int ExpenseTrackerAndHomeNeedsId { get; set; }
        public int Monthly_NeedsId { get; set; }
        public int LoansId { get; set; }
        public int Check_ListId { get; set; }
        public int Family_MembersId { get; set; }
        public int VehicleId { get; set; }
        public int VehileKm_TrackerId { get; set; }
        public int Trip_Check_ListId { get; set; }
        public int Trip_Check_ListId1 { get; set; }
        public int Monthly_NeedsId1 { get; set; }
        public int Family_MembersId1 { get; set; }
        public int Trip_Check_ListId2 { get; set; }
    
        public virtual Loans Loan { get; set; }
        public virtual Check_List Check_List { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual Monthly_Needs Monthly_Needs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseTrackerAndHomeNeeds> ExpenseTrackerAndHomeNeeds { get; set; }
        public virtual Family_Members Family_Members { get; set; }
        public virtual VehileKm_Tracker VehileKm_Tracker { get; set; }
        public virtual Trip_Check_List Trip_Check_List { get; set; }
    }
}
