//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAHN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monthly_Needs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Monthly_Needs()
        {
            this.Home_Needs = new HashSet<Home_Needs>();
        }
    
        public int Id { get; set; }
        public string Location { get; set; }
        public long Amount { get; set; }
        public string Description { get; set; }
        public int Need_NameId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Home_Needs> Home_Needs { get; set; }
        public virtual Need_Name Need_Name { get; set; }
    }
}
