//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAHN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person_Details()
        {
            this.ExpenseTrackers = new HashSet<ExpenseTracker>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int EntityId { get; set; }
        public long PhoneNumber1 { get; set; }
        public long PhoneNumber2 { get; set; }
        public string EmailId { get; set; }
        public string Occupation { get; set; }
        public string OccupativeAddress { get; set; }
        public long Salary { get; set; }
        public int Person_TypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseTracker> ExpenseTrackers { get; set; }
        public virtual Person_Type Person_Type { get; set; }
    }
}
