//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAHN
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThisMonth
    {
        public int Id { get; set; }
        public long Salary_Balance { get; set; }
        public long Amount_Spent { get; set; }
        public int ExpenseTrackerId { get; set; }
    
        public virtual ExpenseTracker ExpenseTracker { get; set; }
    }
}
