//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAHN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip_Check_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip_Check_List()
        {
            this.Home_Needs = new HashSet<Home_Needs>();
        }
    
        public int Id { get; set; }
        public string Thing_Name { get; set; }
        public string Unit { get; set; }
        public string description { get; set; }
        public int Trip_ForId { get; set; }
        public int TakenId { get; set; }
        public int Trip_ForId1 { get; set; }
        public int TakenId1 { get; set; }
    
        public virtual Trip_For Trip_For { get; set; }
        public virtual Taken Taken { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Home_Needs> Home_Needs { get; set; }
    }
}
