//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission_form
    {
        public int Id { get; set; }
        public int Enquiry_TypeId { get; set; }
        public string Department { get; set; }
        public int Student_TypeId { get; set; }
        public int QuotaId { get; set; }
        public long Tenth_Percentage { get; set; }
        public long Plustwo_Percentage { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public long Phone_Num { get; set; }
    
        public virtual Enquiry_Type Enquiry_Type { get; set; }
        public virtual Student_Type Student_Type { get; set; }
        public virtual Quota Quota { get; set; }
    }
}
