//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        public int Id { get; set; }
        public string Property1 { get; set; }
        public long Class_No { get; set; }
        public int Room_TypeId { get; set; }
    
        public virtual Room_Type Room_Type { get; set; }
    }
}
