//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fees
    {
        public int Id { get; set; }
        public long Fee_Amount { get; set; }
        public string Department { get; set; }
        public long Student_Regno { get; set; }
        public string Student_Name { get; set; }
        public string Date { get; set; }
        public long Semester { get; set; }
        public long Year { get; set; }
    }
}
