//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public long Staff_Num { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string Subject_Handling { get; set; }
        public int Staff_TypeId { get; set; }
        public long Phone_No { get; set; }
        public string Email { get; set; }
        public string Teamviewer_Id { get; set; }
    
        public virtual Staff_Type Staff_Type { get; set; }
    }
}
