//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sea
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class studentformContainer : DbContext
    {
        public studentformContainer()
            : base("name=studentformContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admission_form> Admission_form { get; set; }
        public virtual DbSet<Enquiry_Type> Enquiry_Type { get; set; }
        public virtual DbSet<Student_Type> Student_Type { get; set; }
        public virtual DbSet<Quota> Quotas { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Staff_Type> Staff_Type { get; set; }
        public virtual DbSet<Authorities> Authorities { get; set; }
        public virtual DbSet<Classroom> Classrooms { get; set; }
        public virtual DbSet<Room_Type> Room_Type { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<Library> Libraries { get; set; }
        public virtual DbSet<Fees> Fees { get; set; }
    }
}
